# Generated by Django 5.1.1 on 2024-09-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=100)),
                ('is_complated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
