# Generated by Django 5.1.1 on 2024-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('A', 'Acil'), ('Y', 'Yüksek'), ('O', 'Orta'), ('D', 'Düşük')], default='O', max_length=1),
        ),
    ]
