# Generated by Django 5.1.1 on 2024-09-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.TextField(),
        ),
    ]
